export interface Instrument {
    channel: number;
    program: number;
    note: number;
}

const instrumentChannel = 1;

export const instruments: Record<string, Omit<Instrument, "note">> = {
    "Acoustic Grand Piano": { channel: instrumentChannel, program: 0 },
    "Bright Acoustic Piano": { channel: instrumentChannel, program: 1 },
    "Electric Grand Piano": { channel: instrumentChannel, program: 2 },
    "Honky-tonk Piano": { channel: instrumentChannel, program: 3 },
    "Electric Piano 1": { channel: instrumentChannel, program: 4 },
    "Electric Piano 2": { channel: instrumentChannel, program: 5 },
    Harpsichord: { channel: instrumentChannel, program: 6 },
    Clavi: { channel: instrumentChannel, program: 7 },
    Celesta: { channel: instrumentChannel, program: 8 },
    Glockenspiel: { channel: instrumentChannel, program: 9 },
    "Music Box": { channel: instrumentChannel, program: 10 },
    Vibraphone: { channel: instrumentChannel, program: 11 },
    Marimba: { channel: instrumentChannel, program: 12 },
    Xylophone: { channel: instrumentChannel, program: 13 },
    "Tubular Bells": { channel: instrumentChannel, program: 14 },
    Dulcimer: { channel: instrumentChannel, program: 15 },
    "Drawbar Organ": { channel: instrumentChannel, program: 16 },
    "Percussive Organ": { channel: instrumentChannel, program: 17 },
    "Rock Organ": { channel: instrumentChannel, program: 18 },
    "Church Organ": { channel: instrumentChannel, program: 19 },
    "Reed Organ": { channel: instrumentChannel, program: 20 },
    Accordion: { channel: instrumentChannel, program: 21 },
    Harmonica: { channel: instrumentChannel, program: 22 },
    "Tango Accordion": { channel: instrumentChannel, program: 23 },
    "Acoustic Guitar (nylon)": { channel: instrumentChannel, program: 24 },
    "Acoustic Guitar (steel)": { channel: instrumentChannel, program: 25 },
    "Electric Guitar (jazz)": { channel: instrumentChannel, program: 26 },
    "Electric Guitar (clean)": { channel: instrumentChannel, program: 27 },
    "Electric Guitar (muted)": { channel: instrumentChannel, program: 28 },
    "Overdriven Guitar": { channel: instrumentChannel, program: 29 },
    "Distortion Guitar": { channel: instrumentChannel, program: 30 },
    "Guitar harmonics": { channel: instrumentChannel, program: 31 },
    "Acoustic Bass": { channel: instrumentChannel, program: 32 },
    "Electric Bass (finger)": { channel: instrumentChannel, program: 33 },
    "Electric Bass (pick)": { channel: instrumentChannel, program: 34 },
    "Fretless Bass": { channel: instrumentChannel, program: 35 },
    "Slap Bass 1": { channel: instrumentChannel, program: 36 },
    "Slap Bass 2": { channel: instrumentChannel, program: 37 },
    "Synth Bass 1": { channel: instrumentChannel, program: 38 },
    "Synth Bass 2": { channel: instrumentChannel, program: 39 },
    Violin: { channel: instrumentChannel, program: 40 },
    Viola: { channel: instrumentChannel, program: 41 },
    Cello: { channel: instrumentChannel, program: 42 },
    Contrabass: { channel: instrumentChannel, program: 43 },
    "Tremolo Strings": { channel: instrumentChannel, program: 44 },
    "Pizzicato Strings": { channel: instrumentChannel, program: 45 },
    "Orchestral Harp": { channel: instrumentChannel, program: 46 },
    Timpani: { channel: instrumentChannel, program: 47 },
    "String Ensemble 1": { channel: instrumentChannel, program: 48 },
    "String Ensemble 2": { channel: instrumentChannel, program: 49 },
    "SynthStrings 1": { channel: instrumentChannel, program: 50 },
    "SynthStrings 2": { channel: instrumentChannel, program: 51 },
    "Choir Aahs": { channel: instrumentChannel, program: 52 },
    "Voice Oohs": { channel: instrumentChannel, program: 53 },
    "Synth Voice": { channel: instrumentChannel, program: 54 },
    "Orchestra Hit": { channel: instrumentChannel, program: 55 },
    Trumpet: { channel: instrumentChannel, program: 56 },
    Trombone: { channel: instrumentChannel, program: 57 },
    Tuba: { channel: instrumentChannel, program: 58 },
    "Muted Trumpet": { channel: instrumentChannel, program: 59 },
    "French Horn": { channel: instrumentChannel, program: 60 },
    "Brass Section": { channel: instrumentChannel, program: 61 },
    "SynthBrass 1": { channel: instrumentChannel, program: 62 },
    "SynthBrass 2": { channel: instrumentChannel, program: 63 },
    "Soprano Sax": { channel: instrumentChannel, program: 64 },
    "Alto Sax": { channel: instrumentChannel, program: 65 },
    "Tenor Sax": { channel: instrumentChannel, program: 66 },
    "Baritone Sax": { channel: instrumentChannel, program: 67 },
    Oboe: { channel: instrumentChannel, program: 68 },
    "English Horn": { channel: instrumentChannel, program: 69 },
    Bassoon: { channel: instrumentChannel, program: 70 },
    Clarinet: { channel: instrumentChannel, program: 71 },
    Piccolo: { channel: instrumentChannel, program: 72 },
    Flute: { channel: instrumentChannel, program: 73 },
    Recorder: { channel: instrumentChannel, program: 74 },
    "Pan Flute": { channel: instrumentChannel, program: 75 },
    "Blown Bottle": { channel: instrumentChannel, program: 76 },
    Shakuhachi: { channel: instrumentChannel, program: 77 },
    Whistle: { channel: instrumentChannel, program: 78 },
    Ocarina: { channel: instrumentChannel, program: 79 },
    "Lead 1 (square)": { channel: instrumentChannel, program: 80 },
    "Lead 2 (sawtooth)": { channel: instrumentChannel, program: 81 },
    "Lead 3 (calliope)": { channel: instrumentChannel, program: 82 },
    "Lead 4 (chiff)": { channel: instrumentChannel, program: 83 },
    "Lead 5 (charang)": { channel: instrumentChannel, program: 84 },
    "Lead 6 (voice)": { channel: instrumentChannel, program: 85 },
    "Lead 7 (fifths)": { channel: instrumentChannel, program: 86 },
    "Lead 8 (bass + lead)": { channel: instrumentChannel, program: 87 },
    "Pad 1 (new age)": { channel: instrumentChannel, program: 88 },
    "Pad 2 (warm)": { channel: instrumentChannel, program: 89 },
    "Pad 3 (polysynth)": { channel: instrumentChannel, program: 90 },
    "Pad 4 (choir)": { channel: instrumentChannel, program: 91 },
    "Pad 5 (bowed)": { channel: instrumentChannel, program: 92 },
    "Pad 6 (metallic)": { channel: instrumentChannel, program: 93 },
    "Pad 7 (halo)": { channel: instrumentChannel, program: 94 },
    "Pad 8 (sweep)": { channel: instrumentChannel, program: 95 },
    "FX 1 (rain)": { channel: instrumentChannel, program: 96 },
    "FX 2 (soundtrack)": { channel: instrumentChannel, program: 97 },
    "FX 3 (crystal)": { channel: instrumentChannel, program: 98 },
    "FX 4 (atmosphere)": { channel: instrumentChannel, program: 99 },
    "FX 5 (brightness)": { channel: instrumentChannel, program: 100 },
    "FX 6 (goblins)": { channel: instrumentChannel, program: 101 },
    "FX 7 (echoes)": { channel: instrumentChannel, program: 102 },
    "FX 8 (sci-fi)": { channel: instrumentChannel, program: 103 },
    Sitar: { channel: instrumentChannel, program: 104 },
    Banjo: { channel: instrumentChannel, program: 105 },
    Shamisen: { channel: instrumentChannel, program: 106 },
    Koto: { channel: instrumentChannel, program: 107 },
    Kalimba: { channel: instrumentChannel, program: 108 },
    "Bag pipe": { channel: instrumentChannel, program: 109 },
    Fiddle: { channel: instrumentChannel, program: 110 },
    Shanai: { channel: instrumentChannel, program: 111 },
    "Tinkle Bell": { channel: instrumentChannel, program: 112 },
    Agogo: { channel: instrumentChannel, program: 113 },
    "Steel Drums": { channel: instrumentChannel, program: 114 },
    Woodblock: { channel: instrumentChannel, program: 115 },
    "Taiko Drum": { channel: instrumentChannel, program: 116 },
    "Melodic Tom": { channel: instrumentChannel, program: 117 },
    "Synth Drum": { channel: instrumentChannel, program: 118 },
    "Reverse Cymbal": { channel: instrumentChannel, program: 119 },
    "Guitar Fret Noise": { channel: instrumentChannel, program: 120 },
    "Breath Noise": { channel: instrumentChannel, program: 121 },
    Seashore: { channel: instrumentChannel, program: 122 },
    "Bird Tweet": { channel: instrumentChannel, program: 123 },
    "Telephone Ring": { channel: instrumentChannel, program: 124 },
    Helicopter: { channel: instrumentChannel, program: 125 },
    Applause: { channel: instrumentChannel, program: 126 },
    Gunshot: { channel: instrumentChannel, program: 127 },
};

const percussionChannel = 10;
const percussionProgram = 0;

export const percussion: Record<string, Instrument> = {
    "Acoustic Bass Drum": { channel: percussionChannel, program: percussionProgram, note: 35 },
    "Bass Drum 1": { channel: percussionChannel, program: percussionProgram, note: 36 },
    "Side Stick": { channel: percussionChannel, program: percussionProgram, note: 37 },
    "Acoustic Snare": { channel: percussionChannel, program: percussionProgram, note: 38 },
    "Hand Clap": { channel: percussionChannel, program: percussionProgram, note: 39 },
    "Electric Snare": { channel: percussionChannel, program: percussionProgram, note: 40 },
    "Low Floor Tom": { channel: percussionChannel, program: percussionProgram, note: 41 },
    "Closed Hi Hat": { channel: percussionChannel, program: percussionProgram, note: 42 },
    "High Floor Tom": { channel: percussionChannel, program: percussionProgram, note: 43 },
    "Pedal Hi-Hat": { channel: percussionChannel, program: percussionProgram, note: 44 },
    "Low Tom": { channel: percussionChannel, program: percussionProgram, note: 45 },
    "Open Hi-Hat": { channel: percussionChannel, program: percussionProgram, note: 46 },
    "Low-Mid Tom": { channel: percussionChannel, program: percussionProgram, note: 47 },
    "Hi-Mid Tom": { channel: percussionChannel, program: percussionProgram, note: 48 },
    "Crash Cymbal 1": { channel: percussionChannel, program: percussionProgram, note: 49 },
    "High Tom": { channel: percussionChannel, program: percussionProgram, note: 50 },
    "Ride Cymbal 1": { channel: percussionChannel, program: percussionProgram, note: 51 },
    "Chinese Cymbal": { channel: percussionChannel, program: percussionProgram, note: 52 },
    "Ride Bell": { channel: percussionChannel, program: percussionProgram, note: 53 },
    Tambourine: { channel: percussionChannel, program: percussionProgram, note: 54 },
    "Splash Cymbal": { channel: percussionChannel, program: percussionProgram, note: 55 },
    Cowbell: { channel: percussionChannel, program: percussionProgram, note: 56 },
    "Crash Cymbal 2": { channel: percussionChannel, program: percussionProgram, note: 57 },
    Vibraslap: { channel: percussionChannel, program: percussionProgram, note: 58 },
    "Ride Cymbal 2": { channel: percussionChannel, program: percussionProgram, note: 59 },
    "Hi Bongo": { channel: percussionChannel, program: percussionProgram, note: 60 },
    "Low Bongo": { channel: percussionChannel, program: percussionProgram, note: 61 },
    "Mute Hi Conga": { channel: percussionChannel, program: percussionProgram, note: 62 },
    "Open Hi Conga": { channel: percussionChannel, program: percussionProgram, note: 63 },
    "Low Conga": { channel: percussionChannel, program: percussionProgram, note: 64 },
    "High Timbale": { channel: percussionChannel, program: percussionProgram, note: 65 },
    "Low Timbale": { channel: percussionChannel, program: percussionProgram, note: 66 },
    "High Agogo": { channel: percussionChannel, program: percussionProgram, note: 67 },
    "Low Agogo": { channel: percussionChannel, program: percussionProgram, note: 68 },
    Cabasa: { channel: percussionChannel, program: percussionProgram, note: 69 },
    Maracas: { channel: percussionChannel, program: percussionProgram, note: 70 },
    "Short Whistle": { channel: percussionChannel, program: percussionProgram, note: 71 },
    "Long Whistle": { channel: percussionChannel, program: percussionProgram, note: 72 },
    "Short Guiro": { channel: percussionChannel, program: percussionProgram, note: 73 },
    "Long Guiro": { channel: percussionChannel, program: percussionProgram, note: 74 },
    Claves: { channel: percussionChannel, program: percussionProgram, note: 75 },
    "Hi Wood Block": { channel: percussionChannel, program: percussionProgram, note: 76 },
    "Low Wood Block": { channel: percussionChannel, program: percussionProgram, note: 77 },
    "Mute Cuica": { channel: percussionChannel, program: percussionProgram, note: 78 },
    "Open Cuica": { channel: percussionChannel, program: percussionProgram, note: 79 },
    "Mute Triangle": { channel: percussionChannel, program: percussionProgram, note: 80 },
    "Open Triangle": { channel: percussionChannel, program: percussionProgram, note: 81 },
};
