// Generated by ChatGPT :)
export const prompts = [
    `Create a jazz melody inspired by a cat chasing its tail.`,
    `Compose a disco groove that's a tribute to the sound of a malfunctioning printer.`,
    `Create a drum beat inspired by the rhythm of a galloping horse.`,
    `Create a drum beat inspired by the theme song from the TV show "The Office".`,
    `Generate a beat that captures the essence of a chaotic carnival.`,
    `Generate a beat that could be the background music for a chase scene in a spy movie.`,
    `Create a drum beat that could be the opening music for a space-themed video game.`,
    `Generate a beat that's reminiscent of the classic "Mission: Impossible" theme.`,
    `Create a drum beat that's inspired by the rhythm of a steam engine train.`,
    `Create a drum beat that's inspired by the rhythm of a heartbeat.`,
    `Generate a beat that's perfect for an intense boss fight in a video game.`,
    `Create a drum beat that's inspired by the "Jurassic Park" theme song.`,
    `Generate a beat that could be the background music for a dramatic courtroom scene.`,
    `Create a drum beat that's inspired by the rhythm of a thunderstorm.`,
    `Generate a beat that could be the background music for a spooky haunted house scene.`,
    `Generate a beat that's perfect for a high-speed car chase scene in a movie.`,
];
